### ISSUE TITLE
Please update Language File

### ISSUE THREAD

**Issue by Mikeagan** [UnRealDinnerbone/LeatherCows-Fabric#2]
In creative mode on the tab created by this mod you see the following:
itemGroup.leathercows.leathercows

to fix, please change your en_us.lang file from:
"itemgroup.leathercows.leathercows" : "Leather Cows" --> to -->
"itemGroup.leathercows.leathercows" : "Leather Cows"

Case matters in language files.

**Comment by UnRealDinnerbone** [comment]
Fixed new versions should be on curseforge soon
